### ISSUE TITLE
MDLWP Portfolio

### ISSUE THREAD

**Issue by shaleverett** [braginteractive/MDLWP#31]
I bought the MDLWP Portfolio plugin today, and the category filter only works part of the time. I have the MDLWP theme installed, and I am running the following plugins: Material Design Icons, Material Design Login Form, Material Design Social Share and MDLWP Portfolio. My website is shaleverett.com if that is any help. Any help would be much appreciated.

**Comment by braginteractive** [comment]
The category filter looks to be working to me? Nice looking site BTW.

**Comment by shaleverett** [comment]
I opened my browser today, and launched shaleverett.com/portfolio and the category filter will not work. I closed my browser and relaunched the page 10 times, and not one of the times did the filter work. Any suggestions?

**Comment by braginteractive** [comment]
Until I see it messing up on my end, I cant really determine what it going on. When it doesn't work for you, see if there are any console errors. I am going to close this issue, since this is for a plugin and not the theme. Send me an email if you need further help or have any questions. Reply to the email that you received the plugin files from.
